### ISSUE TITLE
Spelling and word modernization 

### ISSUE THREAD

**Issue by thewchan** [gsegol/jules-verne_round-the-moon_ward-lock-co#9]
Ch1.
pyroxyle -> pyroxylin; the former is archaic and the latter is in the M-W, might need to check with Alex to see which to use

Ch2:
indiarubber -> India rubber as per M-W

Ch4:
connaisseur -> If kept in this form, needs French semantics, if changed to "connoisseur", then no semantics needed as it is in the M-W, also in this case remove the <i> tag.

Ch 12:
inclosure -> enclosure; you have changed most of these throughout the book, `inclose` -> `enclose`, we should change these too

Ch 13:
inclosure -> enclosure
chiaro-oscuro -> possibly chiaroscuro, the latter is in the M-W. Check with Alex

Ch 15:
hyperhumbug -> Possibly hyper-humbug instead, but check with Alex
bolis -> Possibly bolide (large meteor), the latter is in the M-W, need to check with Alex.

Ch 16:
incursted -> encrusted

Ch 17: archpieces -> probably arch-pieces? As in pieces of an arch?

Ch 21: bolis -> same as above, need to check with Alex

**Comment by gsegol** [comment]
Done.
bolis is greek.  I marked it as such.
No 'arch pieces' anywhere in Ch 17.  There is 'arch pieces' in that chapter, though.  I left it as such since we tend to remove hyphens rather than add them.

**Comment by thewchan** [comment]
There is an `archpieces` (without space) in chapter 17 line 27, but maybe that's already fixed in your branch.

**Comment by gsegol** [comment]
Could you please give me the full sentence?  We seem to have slightly different line number counts.
Thank you.

Geneviėve
***@***.***

**Comment by thewchan** [comment]
Yep:

`<p>Michel Ardan, however, thought he recognised a heap of ruins, to which he drew Barbicane’s attention. It was situated in about the 80th parallel and 30° longitude. This heap of stones, pretty regularly made, was in the shape of a vast fortress, overlooking one of those long furrows which served as riverbeds in ante-historical times. Not far off rose to a height of 5,646 metres the circular mountain called Short, equal to the Asiatic Caucasus. Michel Ardan, with his habitual ardour, maintained “the evidences” of his fortress. Below he perceived the dismantled ramparts of a town; here the arch of a portico, still intact; there two or three columns lying on their side; farther on a succession of **archpieces**, which must have supported the conduct of an aqueduct; in another part the sunken pillars of a gigantic bridge run into the thickest part of the furrow. He distinguished all that, but with so much imagination in his eyes, through a telescope so fanciful, that his observation cannot be relied upon. And yet who would affirm, who would dare to say, that the amiable fellow had not really seen what his two companions would not see?</p>`

**Comment by gsegol** [comment]
Thanks.
I guessed this is the one I was referring to in my comment on GitHub.  It now is arch pieces.  I push this version to github a moment ago.

Geneviėve
***@***.***

**Comment by gsegol** [comment]
That is the error remaining after se-lint.  I have only changed en-US to en-GB as I did elsewhere.
Is that the problem?



Geneviėve
***@***.***

**Comment by gsegol** [comment]
Geneviėve
***@***.***
